### ISSUE TITLE
MultiheadAttention报错

### ISSUE THREAD

**Issue by carfei** [DrowsyMon/RMFormer#1]
test.py
self.attn = nn.MultiheadAttention(dim,num_heads=1,dropout=0.1,kdim=vdim,vdim=vdim,batch_first=True)
TypeError: __init__() got an unexpected keyword argument 'batch_first'

self.attn = nn.MultiheadAttention(dim,num_heads=1,dropout=0.1,kdim=vdim,vdim=vdim)
File "/root/picasso/gram/RMFormer-main/model/RMFormer.py", line 550, in forward
    x = self.attn(query = qin, key = kin, value = vin)[0]
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/activation.py", line 987, in forward
    attn_mask=attn_mask)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/functional.py", line 4761, in multi_head_attention_forward
    k = k.contiguous().view(-1, bsz * num_heads, head_dim).transpose(0, 1)
RuntimeError: shape '[-1, 29491, 16]' is invalid for input of size 2304

**Comment by DrowsyMon** [comment]
It seems that this issue is due to the older version of PyTorch.
In PyTorch version >= 1.9.0, there is `batch_first` keyword in `nn.MultiheadAttention`
>https://pytorch.org/docs/1.9.0/generated/torch.nn.MultiheadAttention.html?highlight=nn%20multiheadattention#torch.nn.MultiheadAttention

However, for version <= 1.8.1:
>https://pytorch.org/docs/1.8.1/generated/torch.nn.MultiheadAttention.html?highlight=nn%20multiheadattention#torch.nn.MultiheadAttention

It's better to upgrade your PyTorch version >= 1.9.0 

You can also try the code I commented out:
>https://github.com/DrowsyMon/RMFormer/blob/main/model/RMFormer.py#L560
